//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warehouse.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to package.
        /// </summary>
        public static string AddToPackage {
            get {
                return ResourceManager.GetString("AddToPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application error.
        /// </summary>
        public static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application error has occurred.
        /// </summary>
        public static string ApplicationErrorMessage {
            get {
                return ResourceManager.GetString("ApplicationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete.
        /// </summary>
        public static string AreYouSureToDelete {
            get {
                return ResourceManager.GetString("AreYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an order.
        /// </summary>
        public static string AskAddOrder {
            get {
                return ResourceManager.GetString("AskAddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the order.
        /// </summary>
        public static string AskRemoveOrder {
            get {
                return ResourceManager.GetString("AskRemoveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the product.
        /// </summary>
        public static string AskRemoveProduct {
            get {
                return ResourceManager.GetString("AskRemoveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available products.
        /// </summary>
        public static string AvailableProducts {
            get {
                return ResourceManager.GetString("AvailableProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be removed from the package, this product is probably already in offer.
        /// </summary>
        public static string CannotRemovedPackageProductProbablyInOffer {
            get {
                return ResourceManager.GetString("CannotRemovedPackageProductProbablyInOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change flor.
        /// </summary>
        public static string ChangeFlor {
            get {
                return ResourceManager.GetString("ChangeFlor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check data.
        /// </summary>
        public static string CheckData {
            get {
                return ResourceManager.GetString("CheckData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion date.
        /// </summary>
        public static string CompletionDate {
            get {
                return ResourceManager.GetString("CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is required.
        /// </summary>
        public static string ConfirmPasswordIsRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coppy.
        /// </summary>
        public static string Coppy {
            get {
                return ResourceManager.GetString("Coppy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corridor.
        /// </summary>
        public static string Corridor {
            get {
                return ResourceManager.GetString("Corridor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create package.
        /// </summary>
        public static string CreatePackage {
            get {
                return ResourceManager.GetString("CreatePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        public static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is incorrect.
        /// </summary>
        public static string EmailisIncorrect {
            get {
                return ResourceManager.GetString("EmailisIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during moving items.
        /// </summary>
        public static string ErrorDuringMovingItems {
            get {
                return ResourceManager.GetString("ErrorDuringMovingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login window not exist.
        /// </summary>
        public static string ErrorLoginWindowNotExist {
            get {
                return ResourceManager.GetString("ErrorLoginWindowNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window not exist.
        /// </summary>
        public static string ErrorMainWindowNotExist {
            get {
                return ResourceManager.GetString("ErrorMainWindowNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length is .
        /// </summary>
        public static string ErrorMaxLength {
            get {
                return ResourceManager.GetString("ErrorMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords are not the same.
        /// </summary>
        public static string ErrorPasswordsAreNotTheSame {
            get {
                return ResourceManager.GetString("ErrorPasswordsAreNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not active.
        /// </summary>
        public static string ErrorUserIsNotActive {
            get {
                return ResourceManager.GetString("ErrorUserIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while assigning products to the rack.
        /// </summary>
        public static string ErrorWhileAssigningProductsToRack {
            get {
                return ResourceManager.GetString("ErrorWhileAssigningProductsToRack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving.
        /// </summary>
        public static string ErrorWhileSaving {
            get {
                return ResourceManager.GetString("ErrorWhileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist in database.
        /// </summary>
        public static string ExistInDatabase {
            get {
                return ResourceManager.GetString("ExistInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add order.
        /// </summary>
        public static string FailedToAddOrder {
            get {
                return ResourceManager.GetString("FailedToAddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate way.
        /// </summary>
        public static string FailedToGenerateWay {
            get {
                return ResourceManager.GetString("FailedToGenerateWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to prepared.
        /// </summary>
        public static string FailedToPrepared {
            get {
                return ResourceManager.GetString("FailedToPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove.
        /// </summary>
        public static string FailedToRemove {
            get {
                return ResourceManager.GetString("FailedToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reserved.
        /// </summary>
        public static string FailedToReserved {
            get {
                return ResourceManager.GetString("FailedToReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save.
        /// </summary>
        public static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flor.
        /// </summary>
        public static string Flor {
            get {
                return ResourceManager.GetString("Flor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flors.
        /// </summary>
        public static string Flors {
            get {
                return ResourceManager.GetString("Flors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate map.
        /// </summary>
        public static string GenerateMap {
            get {
                return ResourceManager.GetString("GenerateMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item state.
        /// </summary>
        public static string ItemState {
            get {
                return ResourceManager.GetString("ItemState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is required.
        /// </summary>
        public static string LoginIsRequired {
            get {
                return ResourceManager.GetString("LoginIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lp.
        /// </summary>
        public static string Lp {
            get {
                return ResourceManager.GetString("Lp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main settings.
        /// </summary>
        public static string MainSettings {
            get {
                return ResourceManager.GetString("MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        public static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max depth.
        /// </summary>
        public static string MaxDepth {
            get {
                return ResourceManager.GetString("MaxDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max height.
        /// </summary>
        public static string MaxHeight {
            get {
                return ResourceManager.GetString("MaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max weight.
        /// </summary>
        public static string MaxWeight {
            get {
                return ResourceManager.GetString("MaxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max width.
        /// </summary>
        public static string MaxWidth {
            get {
                return ResourceManager.GetString("MaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string MessagePasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("MessagePasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New order.
        /// </summary>
        public static string NewOrder {
            get {
                return ResourceManager.GetString("NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is opened.
        /// </summary>
        public static string OrderIsOpened {
            get {
                return ResourceManager.GetString("OrderIsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders from supplier.
        /// </summary>
        public static string OrdersFromSupplier {
            get {
                return ResourceManager.GetString("OrdersFromSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders to realization in a given month.
        /// </summary>
        public static string OrdersToRealizationInGivenMonth {
            get {
                return ResourceManager.GetString("OrdersToRealizationInGivenMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package contains products, remove them from the rack.
        /// </summary>
        public static string PackageContainsProductsRemoveThemFromRack {
            get {
                return ResourceManager.GetString("PackageContainsProductsRemoveThemFromRack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev page.
        /// </summary>
        public static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product states.
        /// </summary>
        public static string ProductStates {
            get {
                return ResourceManager.GetString("ProductStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racks.
        /// </summary>
        public static string Racks {
            get {
                return ResourceManager.GetString("Racks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realization date.
        /// </summary>
        public static string RealizationDate {
            get {
                return ResourceManager.GetString("RealizationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed order.
        /// </summary>
        public static string RemovedOrder {
            get {
                return ResourceManager.GetString("RemovedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed product.
        /// </summary>
        public static string RemovedProduct {
            get {
                return ResourceManager.GetString("RemovedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove package.
        /// </summary>
        public static string RemovePackage {
            get {
                return ResourceManager.GetString("RemovePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing.
        /// </summary>
        public static string Removing {
            get {
                return ResourceManager.GetString("Removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve products.
        /// </summary>
        public static string ReserveProducts {
            get {
                return ResourceManager.GetString("ReserveProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search product.
        /// </summary>
        public static string SearchProduct {
            get {
                return ResourceManager.GetString("SearchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select unit.
        /// </summary>
        public static string SelectUnit {
            get {
                return ResourceManager.GetString("SelectUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as done.
        /// </summary>
        public static string SetAsDone {
            get {
                return ResourceManager.GetString("SetAsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as received.
        /// </summary>
        public static string SetAsReceived {
            get {
                return ResourceManager.GetString("SetAsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage units.
        /// </summary>
        public static string StorageUnits {
            get {
                return ResourceManager.GetString("StorageUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfull prepared.
        /// </summary>
        public static string SuccesfullPrepared {
            get {
                return ResourceManager.GetString("SuccesfullPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfull reserved.
        /// </summary>
        public static string SuccesfullReserved {
            get {
                return ResourceManager.GetString("SuccesfullReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful created user.
        /// </summary>
        public static string SuccessfulCreatedUser {
            get {
                return ResourceManager.GetString("SuccessfulCreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful removed.
        /// </summary>
        public static string SuccessfulRemoved {
            get {
                return ResourceManager.GetString("SuccessfulRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is empty.
        /// </summary>
        public static string UserIsEmpty {
            get {
                return ResourceManager.GetString("UserIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User settings.
        /// </summary>
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ware house.
        /// </summary>
        public static string WareHouse {
            get {
                return ResourceManager.GetString("WareHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse item.
        /// </summary>
        public static string WarehouseItem {
            get {
                return ResourceManager.GetString("WarehouseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WareHouse items.
        /// </summary>
        public static string WareHouseItems {
            get {
                return ResourceManager.GetString("WareHouseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Way.
        /// </summary>
        public static string Way {
            get {
                return ResourceManager.GetString("Way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wayfinding.
        /// </summary>
        public static string Wayfinding {
            get {
                return ResourceManager.GetString("Wayfinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight discrepancy.
        /// </summary>
        public static string WeightDiscrepancy {
            get {
                return ResourceManager.GetString("WeightDiscrepancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
